### ISSUE TITLE
Show the languages of the project in the issue.

### ISSUE THREAD

**Issue by exhuma** [tevko/practice#9] opened 2014-07-09 15:18 UTC
I've clicked to a few random issues only to see that they are not written in a language I am proficient in.

Having a quick breakdown of the project languages on the displayed ticket would help a lot.

**Comment by tevko** [comment] 2014-07-09 15:19
duplicate of https://github.com/tevko/practice/issues/8

**Closed as completed by tevko** 2014-07-09 15:19 UTC
